### ISSUE TITLE
Z-index changes

### ISSUE THREAD

**Issue by zphixon** [eramdam/firefox-vertical-tabs-on-demand#1]
Hello! This is great. On win 11 however:

![image](https://github.com/eramdam/firefox-vertical-tabs-on-demand/assets/4751549/1616a1ab-4961-4c2d-a3fc-b2735cdc5de5)

I just changed the z-index of the title bar and nav bar and it works fine now

```css
    /* Necessary to tweak layering of titlebar controls */
    & #titlebar {
      z-index: 500;
    }
    & #nav-bar {
      z-index: 499;
    }
```
